//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcoMarketProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Id { get; set; }
        public string AdSoyad { get; set; }
        public string Cinsiyet { get; set; }
        public string Meslek { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public string Email { get; set; }
        public string WebSite { get; set; }
        public Nullable<bool> ReklamMaili { get; set; }
        public string Adres { get; set; }
        public string YasadigiSehir { get; set; }
        public string Telefon { get; set; }
        public string Notlar { get; set; }
    }
}
